// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingMovieTicket_Repository.Entities;

public partial class BookingSeat
{
    public Guid Id { get; set; }

    public Guid BookingId { get; set; }

    public Guid ShowtimeSeatId { get; set; }

    public decimal PriceAtBooking { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual ShowtimeSeat ShowtimeSeat { get; set; }
}