// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BookingMovieTicket_Repository.Entities;

public partial class BookingMovieTicketSystemDbContext : DbContext
{
    public BookingMovieTicketSystemDbContext(DbContextOptions<BookingMovieTicketSystemDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingSeat> BookingSeats { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Seat> Seats { get; set; }

    public virtual DbSet<SeatMap> SeatMaps { get; set; }

    public virtual DbSet<Showtime> Showtimes { get; set; }

    public virtual DbSet<ShowtimeSeat> ShowtimeSeats { get; set; }

    public virtual DbSet<StaffVenue> StaffVenues { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Venue> Venues { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresExtension("pgcrypto");

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("booking_pkey");

            entity.ToTable("booking");

            entity.HasIndex(e => e.Status, "ix_booking_status");

            entity.HasIndex(e => new { e.UserId, e.CreatedAt }, "ix_booking_user_createdat").IsDescending(false, true);

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CheckedInAt).HasColumnName("checked_in_at");
            entity.Property(e => e.ConfirmedAt).HasColumnName("confirmed_at");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.QrCode)
                .HasMaxLength(200)
                .HasColumnName("qr_code");
            entity.Property(e => e.ShowtimeId).HasColumnName("showtime_id");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.TotalAmount)
                .HasPrecision(10, 2)
                .HasColumnName("total_amount");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Showtime).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.ShowtimeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("booking_showtime_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("booking_user_id_fkey");
        });

        modelBuilder.Entity<BookingSeat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("booking_seat_pkey");

            entity.ToTable("booking_seat");

            entity.HasIndex(e => e.ShowtimeSeatId, "uq_booking_seat_showtime_seat").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.BookingId).HasColumnName("booking_id");
            entity.Property(e => e.PriceAtBooking)
                .HasPrecision(10, 2)
                .HasColumnName("price_at_booking");
            entity.Property(e => e.ShowtimeSeatId).HasColumnName("showtime_seat_id");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingSeats)
                .HasForeignKey(d => d.BookingId)
                .HasConstraintName("booking_seat_booking_id_fkey");

            entity.HasOne(d => d.ShowtimeSeat).WithOne(p => p.BookingSeat)
                .HasForeignKey<BookingSeat>(d => d.ShowtimeSeatId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("booking_seat_showtime_seat_id_fkey");
        });

        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("event_pkey");

            entity.ToTable("event");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DurationMinutes).HasColumnName("duration_minutes");
            entity.Property(e => e.PosterUrl)
                .HasMaxLength(500)
                .HasColumnName("poster_url");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("title");
            entity.Property(e => e.VenueId).HasColumnName("venue_id");

            entity.HasOne(d => d.Venue).WithMany(p => p.Events)
                .HasForeignKey(d => d.VenueId)
                .HasConstraintName("event_venue_id_fkey");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("payment_pkey");

            entity.ToTable("payment");

            entity.HasIndex(e => e.BookingId, "uq_payment_booking").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.Amount)
                .HasPrecision(10, 2)
                .HasColumnName("amount");
            entity.Property(e => e.BookingId).HasColumnName("booking_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Method).HasColumnName("method");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.TransactionRef)
                .HasMaxLength(100)
                .HasColumnName("transaction_ref");

            entity.HasOne(d => d.Booking).WithOne(p => p.Payment)
                .HasForeignKey<Payment>(d => d.BookingId)
                .HasConstraintName("payment_booking_id_fkey");
        });

        modelBuilder.Entity<Seat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("seat_pkey");

            entity.ToTable("seat");

            entity.HasIndex(e => new { e.SeatMapId, e.RowLabel, e.Number }, "uq_seat_position").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.Number).HasColumnName("number");
            entity.Property(e => e.RowLabel)
                .IsRequired()
                .HasMaxLength(5)
                .HasColumnName("row_label");
            entity.Property(e => e.SeatMapId).HasColumnName("seat_map_id");
            entity.Property(e => e.SeatType).HasColumnName("seat_type");

            entity.HasOne(d => d.SeatMap).WithMany(p => p.Seats)
                .HasForeignKey(d => d.SeatMapId)
                .HasConstraintName("seat_seat_map_id_fkey");
        });

        modelBuilder.Entity<SeatMap>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("seat_map_pkey");

            entity.ToTable("seat_map");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.Columns).HasColumnName("columns");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Rows).HasColumnName("rows");
            entity.Property(e => e.VenueId).HasColumnName("venue_id");

            entity.HasOne(d => d.Venue).WithMany(p => p.SeatMaps)
                .HasForeignKey(d => d.VenueId)
                .HasConstraintName("seat_map_venue_id_fkey");
        });

        modelBuilder.Entity<Showtime>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("showtime_pkey");

            entity.ToTable("showtime");

            entity.HasIndex(e => new { e.EventId, e.StartTime }, "ix_showtime_event_starttime");

            entity.HasIndex(e => e.StartTime, "ix_showtime_starttime");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.BasePriceStandard)
                .HasPrecision(10, 2)
                .HasColumnName("base_price_standard");
            entity.Property(e => e.BasePriceVip)
                .HasPrecision(10, 2)
                .HasColumnName("base_price_vip");
            entity.Property(e => e.EndTime).HasColumnName("end_time");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.SeatMapId).HasColumnName("seat_map_id");
            entity.Property(e => e.StartTime).HasColumnName("start_time");

            entity.HasOne(d => d.Event).WithMany(p => p.Showtimes)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("showtime_event_id_fkey");

            entity.HasOne(d => d.SeatMap).WithMany(p => p.Showtimes)
                .HasForeignKey(d => d.SeatMapId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("showtime_seat_map_id_fkey");
        });

        modelBuilder.Entity<ShowtimeSeat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("showtime_seat_pkey");

            entity.ToTable("showtime_seat");

            entity.HasIndex(e => new { e.ShowtimeId, e.Status }, "ix_showtime_seat_showtime_status");

            entity.HasIndex(e => new { e.Status, e.HeldUntil }, "ix_showtime_seat_status_helduntil").HasFilter("(status = 1)");

            entity.HasIndex(e => new { e.ShowtimeId, e.SeatId }, "uq_showtime_seat").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.HeldByUserId).HasColumnName("held_by_user_id");
            entity.Property(e => e.HeldUntil).HasColumnName("held_until");
            entity.Property(e => e.Price)
                .HasPrecision(10, 2)
                .HasColumnName("price");
            entity.Property(e => e.SeatId).HasColumnName("seat_id");
            entity.Property(e => e.ShowtimeId).HasColumnName("showtime_id");
            entity.Property(e => e.Status).HasColumnName("status");

            entity.HasOne(d => d.HeldByUser).WithMany(p => p.ShowtimeSeats)
                .HasForeignKey(d => d.HeldByUserId)
                .HasConstraintName("showtime_seat_held_by_user_id_fkey");

            entity.HasOne(d => d.Seat).WithMany(p => p.ShowtimeSeats)
                .HasForeignKey(d => d.SeatId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("showtime_seat_seat_id_fkey");

            entity.HasOne(d => d.Showtime).WithMany(p => p.ShowtimeSeats)
                .HasForeignKey(d => d.ShowtimeId)
                .HasConstraintName("showtime_seat_showtime_id_fkey");
        });

        modelBuilder.Entity<StaffVenue>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("staff_venue_pkey");

            entity.ToTable("staff_venue");

            entity.HasIndex(e => new { e.UserId, e.VenueId }, "uq_staff_venue").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.VenueId).HasColumnName("venue_id");

            entity.HasOne(d => d.User).WithMany(p => p.StaffVenues)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("staff_venue_user_id_fkey");

            entity.HasOne(d => d.Venue).WithMany(p => p.StaffVenues)
                .HasForeignKey(d => d.VenueId)
                .HasConstraintName("staff_venue_venue_id_fkey");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_pkey");

            entity.ToTable("user");

            entity.HasIndex(e => e.Email, "uq_user_email").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("full_name");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("password_hash");
            entity.Property(e => e.Role).HasColumnName("role");
        });

        modelBuilder.Entity<Venue>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("venue_pkey");

            entity.ToTable("venue");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(500)
                .HasColumnName("address");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}