// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingMovieTicket_Repository.Entities;

public partial class Event
{
    public Guid Id { get; set; }

    public Guid VenueId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int DurationMinutes { get; set; }

    public string PosterUrl { get; set; }

    public virtual ICollection<Showtime> Showtimes { get; set; } = new List<Showtime>();

    public virtual Venue Venue { get; set; }
}