// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingMovieTicket_Repository.Entities;

public partial class Payment
{
    public Guid Id { get; set; }

    public Guid BookingId { get; set; }

    public decimal Amount { get; set; }

    public short Status { get; set; }

    public short Method { get; set; }

    public string TransactionRef { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Booking Booking { get; set; }
}