// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingMovieTicket_Repository.Entities;

public partial class Seat
{
    public Guid Id { get; set; }

    public Guid SeatMapId { get; set; }

    public string RowLabel { get; set; }

    public int Number { get; set; }

    public short SeatType { get; set; }

    public virtual SeatMap SeatMap { get; set; }

    public virtual ICollection<ShowtimeSeat> ShowtimeSeats { get; set; } = new List<ShowtimeSeat>();
}