// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingMovieTicket_Repository.Entities;

public partial class SeatMap
{
    public Guid Id { get; set; }

    public Guid VenueId { get; set; }

    public string Name { get; set; }

    public int Rows { get; set; }

    public int Columns { get; set; }

    public virtual ICollection<Seat> Seats { get; set; } = new List<Seat>();

    public virtual ICollection<Showtime> Showtimes { get; set; } = new List<Showtime>();

    public virtual Venue Venue { get; set; }
}