// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingMovieTicket_Repository.Entities;

public partial class ShowtimeSeat
{
    public Guid Id { get; set; }

    public Guid ShowtimeId { get; set; }

    public Guid SeatId { get; set; }

    public short Status { get; set; }

    public decimal Price { get; set; }

    public Guid? HeldByUserId { get; set; }

    public DateTime? HeldUntil { get; set; }

    public virtual BookingSeat BookingSeat { get; set; }

    public virtual User HeldByUser { get; set; }

    public virtual Seat Seat { get; set; }

    public virtual Showtime Showtime { get; set; }
}