// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingMovieTicket_Repository.Entities;

public partial class Showtime
{
    public Guid Id { get; set; }

    public Guid EventId { get; set; }

    public Guid SeatMapId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public decimal BasePriceStandard { get; set; }

    public decimal BasePriceVip { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Event Event { get; set; }

    public virtual SeatMap SeatMap { get; set; }

    public virtual ICollection<ShowtimeSeat> ShowtimeSeats { get; set; } = new List<ShowtimeSeat>();
}