// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingMovieTicket_Repository.Entities;

public partial class StaffVenue
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid VenueId { get; set; }

    public virtual User User { get; set; }

    public virtual Venue Venue { get; set; }
}