// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingMovieTicket_Repository.Entities;

public partial class Venue
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    public virtual ICollection<SeatMap> SeatMaps { get; set; } = new List<SeatMap>();

    public virtual ICollection<StaffVenue> StaffVenues { get; set; } = new List<StaffVenue>();
}